version: '3.8'
services: 
  demo1:
    image: localhost:5000/demo
    ports:
      - 7701:7777
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:7777/"]
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.ip == 192.168.1.128
      resources:
        limits:
          memory: 512M
  demo2:
    image: localhost:5000/demo
    ports:
      - 7702:7777
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:7777/"]
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.ip == 192.168.1.129
      resources:
        limits:
          memory: 512M
